/* empty css                         */
import { a as createComponent, r as renderTemplate, m as maybeRenderHead, b as addAttribute, d as renderComponent } from './astro/server_BWzPTXNg.mjs';
import 'kleur/colors';
import { $ as $$BaseLayout } from './BaseLayout_euznmiol.mjs';
import 'clsx';
import { f as formatPhone, B as BusinessInfo } from './Eli_Mordecai-Logo-216_u2v_MXNV.mjs';
import { $ as $$BannerTitleSection } from './banner-title-section_DZhE5JNK.mjs';

const $$PhoneIcon = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<div class="contact-info-item header-contact-item flex items-center mb-[15px] pl-[10px] min-[1280px]:justify-start min-[1280px]:pl-[50px]"> <div class=" header-link-wrap border-[2px] border-primaryC rounded-[100px] justify-center items-center w-[62px] h-[62px] md:flex"> <img src="/assets/icons/header-call-icon.svg" loading="lazy" alt="Phone Icon"> </div> <div class="header-contact-link-wrap pl-[12px]"> <p class="header-contact-title text-primaryC mb-[0] text-[18px] font-[500] md:text-[18px]">Call Us On:</p> <a${addAttribute(`tel:${BusinessInfo.phone}`, "href")} class="">${formatPhone(BusinessInfo.phone)}</a> </div> </div>`;
}, "D:/Astro/eli-mordecai/src/components/graphics/phone-icon.astro", void 0);

const $$EmailIcon = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<div class="header-contact-item contact-info-item"> <div class=" header-link-wrap border-[2px] border-primaryC rounded-[100px] justify-center items-center w-[62px] h-[62px] md:flex"> <img src="/assets/icons/header-mail-icon.svg" loading="lazy" alt="Email Icon"> </div> <div class="header-contact-link-wrap pl-[12px]"> <p class="header-contact-title text-primaryC mb-[0] text-[18px] font-[500] md:text-[18px]">Email Us On:</p> <a${addAttribute(`mailto:${BusinessInfo.email}`, "href")} class="">${BusinessInfo.email}</a> </div> </div>`;
}, "D:/Astro/eli-mordecai/src/components/graphics/email-icon.astro", void 0);

const $$Contact = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${renderComponent($$result, "BaseLayout", $$BaseLayout, { "pageTitle": "Contact Me", "customDescription": "Lawyer site" }, { "default": ($$result2) => renderTemplate` ${renderComponent($$result2, "BannerTitleSection", $$BannerTitleSection, { "title": "Contact Me" })} ${maybeRenderHead()}<div class="contact-form-section"> <div class="max-w-[100%] px-[30px] min-[480px]:px-[40px] min-[1280px]:max-w-[100%] min-[1280px]:px-[40px] min-[1440px]:max-w-[1440px] min-[1440px]:px-[20px] min-[1920px]:px-0 container mx-auto before:content-[' '] after:content-[' '] before:grid-area-[1/1/2/2] after:grid-area-[1/1/2/2] before:table after:table after:clear-both w-container"> <div class="contact-info-wrap"> <div class="grid md:grid-cols-2 md:gap-x-10 w-full"> <div class="md:border-r-[1px] md:border-r-[rgba(255,255,255,0.3)] md:text-right md:pr-10"> <h3 class="contact-info-title">Los Angeles</h3> <p class="info-office-address">${BusinessInfo.street},<br> ${BusinessInfo.city}, ${BusinessInfo.state} ${BusinessInfo.zip}</p> </div> <div class="mt-10 md:mt-0"> <div class="flex flex-row gap-5"> <div class="flex border-2 border-solid border-primaryC rounded-full justify-center align-center w-[62px] h-[62px] min-w-[62px] p-4 sm:p-5"> <img src="/assets/icons/header-mail-icon.svg" loading="lazy" alt="Email Icon" class=""> </div> <a${addAttribute(`mailto:${BusinessInfo.email}`, "href")} class="contact-intro-link my-auto">${BusinessInfo.email}</a> </div> <div class="flex flex-row gap-5 my-5"> <div class="flex border-2 border-solid border-primaryC rounded-full justify-center align-center w-[62px] h-[62px] min-w-[62px] p-4 sm:p-5"> <img src="/assets/icons/header-call-icon.svg" loading="lazy" alt="Phone Icon" class=""> </div> <a${addAttribute(`tel:${BusinessInfo.phone}`, "href")} class="contact-intro-link">${formatPhone(BusinessInfo.phone)}</a> </div> </div> </div> </div> <div class="contact-form-wrap"> <div class="contact-form-item"> <div class="w-form"> <h2 class="text-primaryC text-3xl sm:text-4xl">Send me a message</h2> ${renderComponent($$result2, "ContactForm", null, { "client:only": "react", "client:component-hydration": "only", "client:component-path": "@/components/contact-form.tsx", "client:component-export": "default" })} <div class="success-message w-form-done"> <div>Thank you! Your submission has been received!</div> </div> <div class="error-message w-form-fail"> <div>Oops! Something went wrong while submitting the form.</div> </div> </div> </div> </div> <div class="contact-links-wrap"> <div class="w-layout-grid contact-links-grid"> <div class="hidden contact-link-infos"> ${renderComponent($$result2, "PhoneIcon", $$PhoneIcon, {})} ${renderComponent($$result2, "EmailIcon", $$EmailIcon, {})} </div> <div class="contact-link-info"></div> </div> </div> </div> </div> ` })}`;
}, "D:/Astro/eli-mordecai/src/pages/contact.astro", void 0);

const $$file = "D:/Astro/eli-mordecai/src/pages/contact.astro";
const $$url = "/contact";

export { $$Contact as default, $$file as file, $$url as url };
